### ISSUE TITLE
error getting mock data for one plate

### ISSUE THREAD

**Issue by MartinFXP** [cbg-ethz/rnaiutilities#20]
works as expected:
```
rnai-query query --db /cluster/work/bewi/members/simondi/data/tix/database/tix_index.db --gene stx3 --featureclass cells --plate dz05-1e --pathogen shigella --study infectx --design p --sample 1000 tix/data/shigella_dz05-1e.tsv
```
produces error message:
```
rnai-query query --db /cluster/work/bewi/members/simondi/data/tix/database/tix_index.db --gene mock --featureclass cells --plate dz05-1e --pathogen shigella --study infectx --design p --sample 1000 tix/data/shigella_dz05-1e.tsv
```
The only difference is the gene. For `mock` it produces the following error:
```
Traceback (most recent call last):
  File "/cluster/home/mpirkl/anaconda3/envs/tix/bin/rnai-query", line 145, in <module>
    cli()
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/bin/rnai-query", line 141, in query
    res.dump(outfile)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/rnaiutilities/rnaiquery/result_set.py", line 72, in dump
    self._dump(tablefileset, io)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/rnaiutilities/rnaiquery/result_set.py", line 96, in _dump
    data, tablefileset.feature_classes)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/rnaiutilities/rnaiquery/result_set.py", line 233, in _get_columns
    data = data.reindex_axis(meta_cols + feat_cols, axis=1, copy=False)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/pandas/core/frame.py", line 2741, in reindex_axis
    limit=limit, fill_value=fill_value)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/pandas/core/generic.py", line 2604, in reindex_axis
    fill_value=fill_value, copy=copy)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/pandas/core/generic.py", line 2627, in _reindex_with_indexers
    copy=copy)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/pandas/core/internals.py", line 3886, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2836, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis
```

It has probably something to do with the fact, that there is more than one `mock` well on the plate, while for a specific gene like `stx3` there is only one well per plate.

**Comment by dirmeier** [comment]
Alright, thanks. I check it out.

**Comment by dirmeier** [comment]
Hi Martin,

this one was harder to find than suspected :). 
I think this 2ec7c80335f2af547627f4f84ae0a933b0e27704 fixed it. 
You can either download the latest [`release`](https://github.com/cbg-ethz/rnaiutilities/releases/tag/v0.1.2) or just clone the repository (which is faster for updating). The main branch should always be working.

Thanks for finding and reporting the bug. Please close this if the issue is resolved and the bug is fixed.

**Comment by MartinFXP** [comment]
I upgraded to the latest version and still get an error via git pull and "pip install ." and get the exact same error message.

```
[INFO/MainProcess/rnaiutilities.rnaiquery.db.sqlite_connection]: Connecting to sqlite db
[INFO/MainProcess/rnaiutilities.rnaiquery.db.db_query]: 
SELECT * 
	FROM (SELECT * FROM meta WHERE (study='infectx') and (pathogen='shigella') and (design='p') and (plate='dz05-1e') and (featureclass='cells')) a1 
	JOIN (SELECT filename FROM gene WHERE (gene='mock')) a2 
	ON (a1.filename = a2.filename);
[INFO/MainProcess/rnaiutilities.rnaiquery.db.database_connection]: Closing connection to db
Traceback (most recent call last):
  File "/cluster/home/mpirkl/anaconda3/envs/tix/bin/rnai-query", line 145, in <module>
    cli()
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/bin/rnai-query", line 141, in query
    res.dump(outfile)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/rnaiutilities/rnaiquery/result_set.py", line 72, in dump
    self._dump(tablefileset, io)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/rnaiutilities/rnaiquery/result_set.py", line 96, in _dump
    data, tablefileset.feature_classes)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/rnaiutilities/rnaiquery/result_set.py", line 233, in _get_columns
    data = data.reindex_axis(meta_cols + feat_cols, axis=1, copy=False)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/pandas/core/frame.py", line 2741, in reindex_axis
    limit=limit, fill_value=fill_value)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/pandas/core/generic.py", line 2604, in reindex_axis
    fill_value=fill_value, copy=copy)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/pandas/core/generic.py", line 2627, in _reindex_with_indexers
    copy=copy)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/pandas/core/internals.py", line 3886, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "/cluster/home/mpirkl/anaconda3/envs/tix/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2836, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis
[INFO/MainProcess] process shutting down
```

**Comment by dirmeier** [comment]
Did you 
```
pip uninstall rnaiutilities && pip install .
```

**Comment by MartinFXP** [comment]
I get all 12 mock controls 23 seconds.
